"""Smart resampling engine for COCO-format datasets."""

from __future__ import annotations

import asyncio
import json
import shutil
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Callable, Coroutine

from augmentor import augment_image, create_augmentation_pipeline
from models import RebalanceTarget


async def rebalance(
    dataset_path: Path,
    targets: list[RebalanceTarget],
    output_path: Path,
    progress_callback: Callable[[str], Coroutine[Any, Any, None]],
) -> None:
    """Rebalance a COCO split by smart downsampling / upsampling.

    The original dataset is NEVER modified — all output goes to *output_path*.
    """
    json_path = dataset_path / "_annotations.coco.json"
    with open(json_path, "r", encoding="utf-8") as fh:
        coco = json.load(fh)

    categories = {cat["id"]: cat["name"] for cat in coco["categories"]}
    name_to_id = {v: k for k, v in categories.items()}

    images_by_id: dict[int, dict] = {img["id"]: img for img in coco["images"]}
    anns_by_image: dict[int, list[dict]] = defaultdict(list)
    for ann in coco["annotations"]:
        anns_by_image[ann["image_id"]].append(ann)

    # Map targets to category ids
    target_map: dict[int, RebalanceTarget] = {}
    for t in targets:
        cid = name_to_id.get(t.class_name)
        if cid is not None:
            target_map[cid] = t

    # Current counts per class
    def _class_counts(ann_map: dict[int, list[dict]]) -> dict[int, int]:
        counts: dict[int, int] = defaultdict(int)
        for anns in ann_map.values():
            for a in anns:
                counts[a["category_id"]] += 1
        return dict(counts)

    # Sets of class ids to up/down-sample
    upsample_ids = {cid for cid, t in target_map.items() if t.strategy == "upsample"}
    downsample_ids = {cid for cid, t in target_map.items() if t.strategy == "downsample"}

    # Snapshot of original counts for accurate progress messages (before any mutations)
    original_counts = _class_counts(anns_by_image)

    # Track which images are retained (start with all)
    retained_image_ids: set[int] = set(images_by_id.keys())

    # ── Single-pass rebalance ────────────────────────────────────────
    MAX_PASSES = 1
    pipeline = create_augmentation_pipeline()
    aug_counter = 0
    # Collect new images / annotations generated by augmentation
    new_images: list[dict] = []
    new_annotations: list[dict] = []
    # Track original image IDs so augmented images are never used as augmentation sources
    original_image_ids: set[int] = set(images_by_id.keys())
    next_image_id = max(images_by_id.keys(), default=0) + 1
    next_ann_id = max((a["id"] for a in coco["annotations"]), default=0) + 1

    for pass_num in range(1, MAX_PASSES + 1):
        await progress_callback(f"Pass {pass_num}/{MAX_PASSES} — computing scores...")

        # Rebuild current annotation map (retained only + new)
        current_ann_map: dict[int, list[dict]] = defaultdict(list)
        for img_id in retained_image_ids:
            current_ann_map[img_id] = list(anns_by_image.get(img_id, []))
        for img in new_images:
            # new_images already have their anns in anns_by_image via augmentation
            pass  # anns already linked in anns_by_image

        counts = _class_counts(
            {iid: anns_by_image[iid] for iid in retained_image_ids}
        )
        # Include new augmented annotations
        for ann in new_annotations:
            counts[ann["category_id"]] = counts.get(ann["category_id"], 0)
        # Recount properly including new annotations
        aug_img_ids = {img["id"] for img in new_images}
        for img_id in aug_img_ids:
            for a in anns_by_image.get(img_id, []):
                counts[a["category_id"]] = counts.get(a["category_id"], 0) + 1

        # Check if we are within 5% tolerance
        all_ok = True
        for cid, t in target_map.items():
            current = counts.get(cid, 0)
            if t.target_count > 0 and abs(current - t.target_count) / t.target_count > 0.05:
                all_ok = False
                break
        if all_ok and pass_num > 1:
            await progress_callback("All classes within 5% of target. Done.")
            break

        # ── DOWNSAMPLE ──────────────────────────────────────────────
        for cid in downsample_ids:
            t = target_map[cid]
            current = counts.get(cid, 0)
            if current <= t.target_count:
                continue

            await progress_callback(
                f"Downsampling {categories[cid]}: {original_counts.get(cid, 0)} -> {t.target_count}"
            )

            # Score retained images that contain this class
            # Hard skip: never remove an image that contains any minority class annotation
            scored: list[tuple[int, float]] = []
            for img_id in list(retained_image_ids):
                img_anns = anns_by_image.get(img_id, [])
                if not img_anns:
                    continue
                if any(a["category_id"] in upsample_ids for a in img_anns):
                    continue
                total = len(img_anns)
                target_count_in_img = sum(
                    1 for a in img_anns if a["category_id"] == cid
                )
                if target_count_in_img == 0:
                    continue
                removal_score = target_count_in_img / total
                scored.append((img_id, removal_score))

            scored.sort(key=lambda x: x[1], reverse=True)

            removed = 0
            needed = current - t.target_count
            for img_id, _ in scored:
                if removed >= needed:
                    break
                img_anns = anns_by_image.get(img_id, [])
                class_anns_in_img = sum(
                    1 for a in img_anns if a["category_id"] == cid
                )
                retained_image_ids.discard(img_id)
                removed += class_anns_in_img
                # Update counts for all classes in this image
                for a in img_anns:
                    counts[a["category_id"]] = max(
                        0, counts.get(a["category_id"], 0) - 1
                    )

        # ── UPSAMPLE ───────────────────────────────────────────────
        for cid in upsample_ids:
            t = target_map[cid]
            current = counts.get(cid, 0)
            if current >= t.target_count:
                continue

            await progress_callback(
                f"Upsampling {categories[cid]}: {original_counts.get(cid, 0)} -> {t.target_count}"
            )

            # Score ORIGINAL retained images containing this class
            # (never augment from already-augmented images — quality degrades)
            scored: list[tuple[int, float]] = []
            for img_id in retained_image_ids & original_image_ids:
                img_anns = anns_by_image.get(img_id, [])
                total = len(img_anns)
                if total == 0:
                    continue
                minority_in_img = sum(
                    1 for a in img_anns if a["category_id"] == cid
                )
                if minority_in_img == 0:
                    continue
                scored.append((img_id, minority_in_img / total))

            scored.sort(key=lambda x: x[1], reverse=True)

            if not scored:
                await progress_callback(
                    f"No images available to upsample {categories[cid]}."
                )
                continue

            needed = t.target_count - current

            # Build the list of (img_id, prefix) jobs to run in parallel
            jobs: list[tuple[int, str]] = []
            idx = 0
            estimated_added = 0
            while estimated_added < needed and scored:
                img_id, _ = scored[idx % len(scored)]
                img_anns = anns_by_image.get(img_id, [])
                prefix = f"aug{aug_counter:05d}_"
                aug_counter += 1
                jobs.append((img_id, prefix))
                estimated_added += sum(1 for a in img_anns if a["category_id"] == cid)
                idx += 1

            # Run augmentations in parallel via thread pool
            def _do_aug(job: tuple[int, str]):
                jid, jpfx = job
                img_meta = images_by_id[jid]
                img_file = dataset_path / img_meta["file_name"]
                # Augmented images from earlier passes live in output_path, not dataset_path
                if not img_file.exists():
                    img_file = output_path / img_meta["file_name"]
                img_anns = anns_by_image.get(jid, [])
                return jid, jpfx, augment_image(
                    image_path=img_file,
                    annotations=img_anns,
                    pipeline=pipeline,
                    output_dir=output_path,
                    prefix=jpfx,
                )

            loop = asyncio.get_event_loop()
            with ThreadPoolExecutor(max_workers=16) as pool:
                futures = [loop.run_in_executor(pool, _do_aug, job) for job in jobs]
                results = await asyncio.gather(*futures, return_exceptions=True)

            for res in results:
                if isinstance(res, Exception):
                    await progress_callback(f"Augmentation error: {res}")
                    continue
                src_img_id, _, (new_path, new_ann_dicts) = res
                img_meta = images_by_id[src_img_id]

                new_img_entry = {
                    "id": next_image_id,
                    "file_name": new_path.name,
                    "width": img_meta.get("width", 0),
                    "height": img_meta.get("height", 0),
                }
                images_by_id[next_image_id] = new_img_entry
                new_images.append(new_img_entry)

                aug_anns: list[dict] = []
                for ad in new_ann_dicts:
                    ann_entry = {
                        "id": next_ann_id,
                        "image_id": next_image_id,
                        "category_id": ad["category_id"],
                        "segmentation": ad["segmentation"],
                        "bbox": ad["bbox"],
                        "area": ad["area"],
                        "iscrowd": ad.get("iscrowd", 0),
                    }
                    aug_anns.append(ann_entry)
                    new_annotations.append(ann_entry)
                    next_ann_id += 1

                anns_by_image[next_image_id] = aug_anns
                retained_image_ids.add(next_image_id)
                next_image_id += 1

                for a in aug_anns:
                    counts[a["category_id"]] = counts.get(a["category_id"], 0) + 1

    # ── Write output ────────────────────────────────────────────────
    await progress_callback("Writing rebalanced dataset...")
    output_path.mkdir(parents=True, exist_ok=True)

    # Copy retained original images in parallel
    def _copy(img_id: int) -> None:
        meta = images_by_id[img_id]
        src = dataset_path / meta["file_name"]
        dst = output_path / meta["file_name"]
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)

    loop = asyncio.get_event_loop()
    with ThreadPoolExecutor(max_workers=16) as pool:
        copy_futures = [loop.run_in_executor(pool, _copy, iid) for iid in retained_image_ids]
        await asyncio.gather(*copy_futures)

    # Build new COCO JSON
    final_images = [images_by_id[iid] for iid in sorted(retained_image_ids)]
    final_annotations: list[dict] = []
    ann_id = 1
    for iid in sorted(retained_image_ids):
        for a in anns_by_image.get(iid, []):
            a_copy = dict(a)
            a_copy["id"] = ann_id
            final_annotations.append(a_copy)
            ann_id += 1

    out_coco = {
        "images": final_images,
        "annotations": final_annotations,
        "categories": coco["categories"],
    }
    out_json = output_path / "_annotations.coco.json"
    with open(out_json, "w", encoding="utf-8") as fh:
        json.dump(out_coco, fh, indent=2)

    # Summary
    final_counts = _class_counts(
        {iid: anns_by_image[iid] for iid in retained_image_ids}
    )
    summary_lines = [
        f"  {categories.get(cid, cid)}: {cnt}" for cid, cnt in sorted(final_counts.items())
    ]
    await progress_callback(
        f"Rebalancing complete. Output: {output_path}\n"
        f"Final distribution:\n" + "\n".join(summary_lines)
    )
